apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-cluster
  namespace: default # Or a dedicated database namespace
  labels:
    app: etcd
spec:
  replicas: 3
  serviceName: "etcd-cluster"
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: k8s.gcr.io/etcd:3.5.1-0 # Example image
        command:
        - etcd
        - --name=$(HOSTNAME)
        - --data-dir=/var/lib/etcd
        - --initial-advertise-peer-urls=http://$(HOSTNAME).etcd-cluster.$(NAMESPACE).svc.cluster.local:2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(HOSTNAME).etcd-cluster.$(NAMESPACE).svc.cluster.local:2379
        - --initial-cluster-token=etcd-cluster-1
        - --initial-cluster=etcd-cluster-0=http://etcd-cluster-0.etcd-cluster.$(NAMESPACE).svc.cluster.local:2380,etcd-cluster-1=http://etcd-cluster-1.etcd-cluster.$(NAMESPACE).svc.cluster.local:2380,etcd-cluster-2=http://etcd-cluster-2.etcd-cluster.$(NAMESPACE).svc.cluster.local:2380
        - --initial-cluster-state=new
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-data
          mountPath: /var/lib/etcd
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-data-$(HOSTNAME)
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard # Or appropriate storage class
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  namespace: default # Or a dedicated database namespace
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: etcd