groups:
- name: ses_agent_metrics
  rules:
  # Rate of token usage per agent/model/tenant
  - record: ses:agent_token_usage:rate5m
    expr: sum by (tenant_id, agent_name, model_used) (rate(agent_token_usage_total[5m]))

  # P95 execution time per agent/tenant
  - record: ses:agent_execution_time_seconds:p95_5m
    expr: histogram_quantile(0.95, sum by (tenant_id, agent_name, le) (rate(agent_execution_time_seconds_bucket[5m])))

  # Success rate per agent/tenant
  - record: ses:agent_success_rate:ratio5m
    expr: >
      sum by (tenant_id, agent_name) (rate(agent_task_status_total{status="success"}[5m]))
      /
      sum by (tenant_id, agent_name) (rate(agent_task_status_total[5m]))

  # P95 vector search latency per query type/tenant
  - record: ses:vector_recall_latency_seconds:p95_5m
    expr: histogram_quantile(0.95, sum by (tenant_id, query_type, le) (rate(vector_search_duration_seconds_bucket[5m])))

  # Average semantic match score (if applicable) per agent/template
  - record: ses:agent_semantic_match_score:avg5m
    expr: >
      avg by (tenant_id, agent_name, prompt_template_id) (
        rate(agent_semantic_match_score_sum[5m])
        /
        rate(agent_semantic_match_score_count[5m])
      )

  # Distribution of user feedback scores per agent
  - record: ses:feedback_score:distribution_rate5m
    expr: sum by (tenant_id, agent_name, score) (rate(agent_feedback_score_total[5m]))

  # Estimated LLM cost rate per agent/model/tenant
  - record: ses:llm_cost_usd:rate1h
    expr: sum by (tenant_id, agent_name, model_used) (rate(llm_cost_usd_total[1h]))