packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # include specific services
  - 'connector-service'
  - 'marketplace-service'
  # exclude packages that are inside test directories
  - '!**/test/**'