import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider"; // Import our client component wrapper
import "./globals.css";
import Topbar from "../../packages/ui/src/Topbar/Topbar";
import Sidebar from "../../packages/ui/src/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-inter bg-background text-onBackground">
      <body className={inter.className}>
        <AuthProvider> {/* Use the client component wrapper */}
          <Topbar />
          <div className="flex">
            <Sidebar className="w-64 hidden lg:block" />
            <main className="flex-1 container p-4 lg:p-6">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
