#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Define the path to the Helm chart
CHART_PATH="../../helm/ses-orchestration" # Adjusted path relative to this test script

# 1. Lint the Helm chart
echo "Linting Helm chart at ${CHART_PATH}..."
helm lint "${CHART_PATH}"
echo "Helm lint completed successfully."

# 2. Template the Helm chart and check for Rollout kinds
# This assumes that the orchestrator-rollout.yaml and agent-runner-rollout.yaml
# are indeed generated as part of the helm template output.
# If they are separate files applied by Terraform's kubernetes_manifest,
# this specific grep might not find them unless they are also part of the chart's direct templates.
# The current setup has them as separate files in the templates/ directory,
# so helm template should output them.
echo "Templating Helm chart and checking for Rollout kinds..."
TEMPLATE_OUTPUT=$(helm template ses-release "${CHART_PATH}")

# Check if the output contains "kind: Rollout"
if echo "${TEMPLATE_OUTPUT}" | grep -q "kind: Rollout"; then
  echo "Found 'kind: Rollout' in Helm template output."
else
  echo "ERROR: Did not find 'kind: Rollout' in Helm template output."
  # echo "Full template output:"
  # echo "${TEMPLATE_OUTPUT}" # Uncomment for debugging
  exit 1
fi

# Optional: More specific checks for your Rollout resources
if echo "${TEMPLATE_OUTPUT}" | grep -q "name: orchestrator-rollout-placeholder"; then
  echo "Found 'orchestrator-rollout-placeholder' in Helm template output."
else
  echo "WARNING: Did not find 'orchestrator-rollout-placeholder' in Helm template output."
  # This might be a warning if the name is dynamically generated by Helm common chart logic.
fi

if echo "${TEMPLATE_OUTPUT}" | grep -q "name: agent-runner-rollout-placeholder"; then
  echo "Found 'agent-runner-rollout-placeholder' in Helm template output."
else
  echo "WARNING: Did not find 'agent-runner-rollout-placeholder' in Helm template output."
fi


echo "Helm template tests completed successfully."
echo "All GitOps & Infra as Code tests passed."