# Placeholder for agent-runner-rollout.yaml
# This file is referenced by Terraform in main.tf.
# It should contain a valid Kubernetes manifest, likely an Argo Rollout definition.
# Example minimal Argo Rollout (replace with actual definition):
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: agent-runner-rollout-placeholder
  labels:
    app.kubernetes.io/name: agent-runner
    app.kubernetes.io/instance: ses-orchestration
    app.kubernetes.io/component: application
spec:
  replicas: {{ .Values.agentRunner.replicas | default 1 }}
  selector:
    matchLabels:
      app: agent-runner-placeholder # Should match template spec
  template:
    metadata:
      labels:
        app: agent-runner-placeholder # Should match selector
    spec:
      containers:
      - name: agent-runner
        image: "{{ .Values.agentRunner.image.repository }}:{{ .Values.agentRunner.image.tag }}"
        ports:
        - containerPort: 8081 # Example port
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: { duration: 1m } # Example: pause for 1 minute
      - setWeight: 50
      - pause: { duration: 1m }